language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
install: 
  - pip install -r requirements.txt --use-mirrors
  - "if [[ $TRAVIS_PYTHON_VERSION != '3.2' ]]; then pip install -i http://simple.crate.io Pillow; fi"
script:  
  - nosetests tests -s
